/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ParaImobiliariasRouteImport } from './routes/para-imobiliarias'
import { Route as ParaDesignersRouteImport } from './routes/para-designers'
import { Route as ParaArquitetosRouteImport } from './routes/para-arquitetos'
import { Route as OrcamentoDesignInterioresRouteImport } from './routes/orcamento-design-interiores'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as EstilosStyleSlugRouteImport } from './routes/estilos.$styleSlug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AmbientesRoomSlugRouteImport } from './routes/ambientes.$roomSlug'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminProjetosRouteImport } from './routes/admin.projetos'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminInsightsRouteImport } from './routes/admin.insights'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaImobiliariasRoute = ParaImobiliariasRouteImport.update({
  id: '/para-imobiliarias',
  path: '/para-imobiliarias',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaDesignersRoute = ParaDesignersRouteImport.update({
  id: '/para-designers',
  path: '/para-designers',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaArquitetosRoute = ParaArquitetosRouteImport.update({
  id: '/para-arquitetos',
  path: '/para-arquitetos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoDesignInterioresRoute =
  OrcamentoDesignInterioresRouteImport.update({
    id: '/orcamento-design-interiores',
    path: '/orcamento-design-interiores',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const EstilosStyleSlugRoute = EstilosStyleSlugRouteImport.update({
  id: '/estilos/$styleSlug',
  path: '/estilos/$styleSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbientesRoomSlugRoute = AmbientesRoomSlugRouteImport.update({
  id: '/ambientes/$roomSlug',
  path: '/ambientes/$roomSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjetosRoute = AdminProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/orcamento-design-interiores': typeof OrcamentoDesignInterioresRoute
  '/para-arquitetos': typeof ParaArquitetosRoute
  '/para-designers': typeof ParaDesignersRoute
  '/para-imobiliarias': typeof ParaImobiliariasRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/ambientes/$roomSlug': typeof AmbientesRoomSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/estilos/$styleSlug': typeof EstilosStyleSlugRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/orcamento-design-interiores': typeof OrcamentoDesignInterioresRoute
  '/para-arquitetos': typeof ParaArquitetosRoute
  '/para-designers': typeof ParaDesignersRoute
  '/para-imobiliarias': typeof ParaImobiliariasRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/ambientes/$roomSlug': typeof AmbientesRoomSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/estilos/$styleSlug': typeof EstilosStyleSlugRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/orcamento-design-interiores': typeof OrcamentoDesignInterioresRoute
  '/para-arquitetos': typeof ParaArquitetosRoute
  '/para-designers': typeof ParaDesignersRoute
  '/para-imobiliarias': typeof ParaImobiliariasRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/ambientes/$roomSlug': typeof AmbientesRoomSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/estilos/$styleSlug': typeof EstilosStyleSlugRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/legal'
    | '/login'
    | '/orcamento-design-interiores'
    | '/para-arquitetos'
    | '/para-designers'
    | '/para-imobiliarias'
    | '/pricing'
    | '/reset-password'
    | '/projetos'
    | '/admin/insights'
    | '/admin/leads'
    | '/admin/projetos'
    | '/admin/usuarios'
    | '/ambientes/$roomSlug'
    | '/auth/callback'
    | '/estilos/$styleSlug'
    | '/p/$projectId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal'
    | '/login'
    | '/orcamento-design-interiores'
    | '/para-arquitetos'
    | '/para-designers'
    | '/para-imobiliarias'
    | '/pricing'
    | '/reset-password'
    | '/projetos'
    | '/admin/insights'
    | '/admin/leads'
    | '/admin/projetos'
    | '/admin/usuarios'
    | '/ambientes/$roomSlug'
    | '/auth/callback'
    | '/estilos/$styleSlug'
    | '/p/$projectId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/legal'
    | '/login'
    | '/orcamento-design-interiores'
    | '/para-arquitetos'
    | '/para-designers'
    | '/para-imobiliarias'
    | '/pricing'
    | '/reset-password'
    | '/_authenticated/projetos'
    | '/admin/insights'
    | '/admin/leads'
    | '/admin/projetos'
    | '/admin/usuarios'
    | '/ambientes/$roomSlug'
    | '/auth/callback'
    | '/estilos/$styleSlug'
    | '/p/$projectId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  OrcamentoDesignInterioresRoute: typeof OrcamentoDesignInterioresRoute
  ParaArquitetosRoute: typeof ParaArquitetosRoute
  ParaDesignersRoute: typeof ParaDesignersRoute
  ParaImobiliariasRoute: typeof ParaImobiliariasRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AmbientesRoomSlugRoute: typeof AmbientesRoomSlugRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EstilosStyleSlugRoute: typeof EstilosStyleSlugRoute
  PProjectIdRoute: typeof PProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-imobiliarias': {
      id: '/para-imobiliarias'
      path: '/para-imobiliarias'
      fullPath: '/para-imobiliarias'
      preLoaderRoute: typeof ParaImobiliariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-designers': {
      id: '/para-designers'
      path: '/para-designers'
      fullPath: '/para-designers'
      preLoaderRoute: typeof ParaDesignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-arquitetos': {
      id: '/para-arquitetos'
      path: '/para-arquitetos'
      fullPath: '/para-arquitetos'
      preLoaderRoute: typeof ParaArquitetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento-design-interiores': {
      id: '/orcamento-design-interiores'
      path: '/orcamento-design-interiores'
      fullPath: '/orcamento-design-interiores'
      preLoaderRoute: typeof OrcamentoDesignInterioresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estilos/$styleSlug': {
      id: '/estilos/$styleSlug'
      path: '/estilos/$styleSlug'
      fullPath: '/estilos/$styleSlug'
      preLoaderRoute: typeof EstilosStyleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambientes/$roomSlug': {
      id: '/ambientes/$roomSlug'
      path: '/ambientes/$roomSlug'
      fullPath: '/ambientes/$roomSlug'
      preLoaderRoute: typeof AmbientesRoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projetos': {
      id: '/admin/projetos'
      path: '/projetos'
      fullPath: '/admin/projetos'
      preLoaderRoute: typeof AdminProjetosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProjetosRoute: AuthenticatedProjetosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminProjetosRoute: typeof AdminProjetosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInsightsRoute: AdminInsightsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminProjetosRoute: AdminProjetosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  OrcamentoDesignInterioresRoute: OrcamentoDesignInterioresRoute,
  ParaArquitetosRoute: ParaArquitetosRoute,
  ParaDesignersRoute: ParaDesignersRoute,
  ParaImobiliariasRoute: ParaImobiliariasRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AmbientesRoomSlugRoute: AmbientesRoomSlugRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EstilosStyleSlugRoute: EstilosStyleSlugRoute,
  PProjectIdRoute: PProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
