/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ParaImobiliariasRouteImport } from './routes/para-imobiliarias'
import { Route as ParaDesignersRouteImport } from './routes/para-designers'
import { Route as ParaArquitetosRouteImport } from './routes/para-arquitetos'
import { Route as OrcamentoDesignInterioresRouteImport } from './routes/orcamento-design-interiores'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VsPlanner5dRouteImport } from './routes/vs.planner-5d'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as EstilosStyleSlugRouteImport } from './routes/estilos.$styleSlug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AmbientesRoomSlugRouteImport } from './routes/ambientes.$roomSlug'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminReceitaRouteImport } from './routes/admin.receita'
import { Route as AdminProjetosRouteImport } from './routes/admin.projetos'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminInsightsRouteImport } from './routes/admin.insights'
import { Route as AdminCreditosRouteImport } from './routes/admin.creditos'
import { Route as AdminAfiliadosRouteImport } from './routes/admin.afiliados'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as EstilosStyleSlugRoomSlugRouteImport } from './routes/estilos.$styleSlug.$roomSlug'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaImobiliariasRoute = ParaImobiliariasRouteImport.update({
  id: '/para-imobiliarias',
  path: '/para-imobiliarias',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaDesignersRoute = ParaDesignersRouteImport.update({
  id: '/para-designers',
  path: '/para-designers',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaArquitetosRoute = ParaArquitetosRouteImport.update({
  id: '/para-arquitetos',
  path: '/para-arquitetos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoDesignInterioresRoute =
  OrcamentoDesignInterioresRouteImport.update({
    id: '/orcamento-design-interiores',
    path: '/orcamento-design-interiores',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VsPlanner5dRoute = VsPlanner5dRouteImport.update({
  id: '/vs/planner-5d',
  path: '/vs/planner-5d',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const EstilosStyleSlugRoute = EstilosStyleSlugRouteImport.update({
  id: '/estilos/$styleSlug',
  path: '/estilos/$styleSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbientesRoomSlugRoute = AmbientesRoomSlugRouteImport.update({
  id: '/ambientes/$roomSlug',
  path: '/ambientes/$roomSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceitaRoute = AdminReceitaRouteImport.update({
  id: '/receita',
  path: '/receita',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjetosRoute = AdminProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditosRoute = AdminCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAfiliadosRoute = AdminAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const EstilosStyleSlugRoomSlugRoute =
  EstilosStyleSlugRoomSlugRouteImport.update({
    id: '/$roomSlug',
    path: '/$roomSlug',
    getParentRoute: () => EstilosStyleSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/orcamento-design-interiores': typeof OrcamentoDesignInterioresRoute
  '/para-arquitetos': typeof ParaArquitetosRoute
  '/para-designers': typeof ParaDesignersRoute
  '/para-imobiliarias': typeof ParaImobiliariasRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/creditos': typeof AdminCreditosRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/receita': typeof AdminReceitaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/ambientes/$roomSlug': typeof AmbientesRoomSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/estilos/$styleSlug': typeof EstilosStyleSlugRouteWithChildren
  '/p/$projectId': typeof PProjectIdRoute
  '/vs/planner-5d': typeof VsPlanner5dRoute
  '/admin/': typeof AdminIndexRoute
  '/estilos/$styleSlug/$roomSlug': typeof EstilosStyleSlugRoomSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/orcamento-design-interiores': typeof OrcamentoDesignInterioresRoute
  '/para-arquitetos': typeof ParaArquitetosRoute
  '/para-designers': typeof ParaDesignersRoute
  '/para-imobiliarias': typeof ParaImobiliariasRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/creditos': typeof AdminCreditosRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/receita': typeof AdminReceitaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/ambientes/$roomSlug': typeof AmbientesRoomSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/estilos/$styleSlug': typeof EstilosStyleSlugRouteWithChildren
  '/p/$projectId': typeof PProjectIdRoute
  '/vs/planner-5d': typeof VsPlanner5dRoute
  '/admin': typeof AdminIndexRoute
  '/estilos/$styleSlug/$roomSlug': typeof EstilosStyleSlugRoomSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/orcamento-design-interiores': typeof OrcamentoDesignInterioresRoute
  '/para-arquitetos': typeof ParaArquitetosRoute
  '/para-designers': typeof ParaDesignersRoute
  '/para-imobiliarias': typeof ParaImobiliariasRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/creditos': typeof AdminCreditosRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/receita': typeof AdminReceitaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/ambientes/$roomSlug': typeof AmbientesRoomSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/estilos/$styleSlug': typeof EstilosStyleSlugRouteWithChildren
  '/p/$projectId': typeof PProjectIdRoute
  '/vs/planner-5d': typeof VsPlanner5dRoute
  '/admin/': typeof AdminIndexRoute
  '/estilos/$styleSlug/$roomSlug': typeof EstilosStyleSlugRoomSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/legal'
    | '/login'
    | '/orcamento-design-interiores'
    | '/para-arquitetos'
    | '/para-designers'
    | '/para-imobiliarias'
    | '/pricing'
    | '/reset-password'
    | '/minha-conta'
    | '/projetos'
    | '/admin/afiliados'
    | '/admin/creditos'
    | '/admin/insights'
    | '/admin/leads'
    | '/admin/projetos'
    | '/admin/receita'
    | '/admin/usuarios'
    | '/ambientes/$roomSlug'
    | '/auth/callback'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/estilos/$styleSlug'
    | '/p/$projectId'
    | '/vs/planner-5d'
    | '/admin/'
    | '/estilos/$styleSlug/$roomSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal'
    | '/login'
    | '/orcamento-design-interiores'
    | '/para-arquitetos'
    | '/para-designers'
    | '/para-imobiliarias'
    | '/pricing'
    | '/reset-password'
    | '/minha-conta'
    | '/projetos'
    | '/admin/afiliados'
    | '/admin/creditos'
    | '/admin/insights'
    | '/admin/leads'
    | '/admin/projetos'
    | '/admin/receita'
    | '/admin/usuarios'
    | '/ambientes/$roomSlug'
    | '/auth/callback'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/estilos/$styleSlug'
    | '/p/$projectId'
    | '/vs/planner-5d'
    | '/admin'
    | '/estilos/$styleSlug/$roomSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/legal'
    | '/login'
    | '/orcamento-design-interiores'
    | '/para-arquitetos'
    | '/para-designers'
    | '/para-imobiliarias'
    | '/pricing'
    | '/reset-password'
    | '/_authenticated/minha-conta'
    | '/_authenticated/projetos'
    | '/admin/afiliados'
    | '/admin/creditos'
    | '/admin/insights'
    | '/admin/leads'
    | '/admin/projetos'
    | '/admin/receita'
    | '/admin/usuarios'
    | '/ambientes/$roomSlug'
    | '/auth/callback'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/estilos/$styleSlug'
    | '/p/$projectId'
    | '/vs/planner-5d'
    | '/admin/'
    | '/estilos/$styleSlug/$roomSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  OrcamentoDesignInterioresRoute: typeof OrcamentoDesignInterioresRoute
  ParaArquitetosRoute: typeof ParaArquitetosRoute
  ParaDesignersRoute: typeof ParaDesignersRoute
  ParaImobiliariasRoute: typeof ParaImobiliariasRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AmbientesRoomSlugRoute: typeof AmbientesRoomSlugRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  EstilosStyleSlugRoute: typeof EstilosStyleSlugRouteWithChildren
  PProjectIdRoute: typeof PProjectIdRoute
  VsPlanner5dRoute: typeof VsPlanner5dRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-imobiliarias': {
      id: '/para-imobiliarias'
      path: '/para-imobiliarias'
      fullPath: '/para-imobiliarias'
      preLoaderRoute: typeof ParaImobiliariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-designers': {
      id: '/para-designers'
      path: '/para-designers'
      fullPath: '/para-designers'
      preLoaderRoute: typeof ParaDesignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-arquitetos': {
      id: '/para-arquitetos'
      path: '/para-arquitetos'
      fullPath: '/para-arquitetos'
      preLoaderRoute: typeof ParaArquitetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento-design-interiores': {
      id: '/orcamento-design-interiores'
      path: '/orcamento-design-interiores'
      fullPath: '/orcamento-design-interiores'
      preLoaderRoute: typeof OrcamentoDesignInterioresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vs/planner-5d': {
      id: '/vs/planner-5d'
      path: '/vs/planner-5d'
      fullPath: '/vs/planner-5d'
      preLoaderRoute: typeof VsPlanner5dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estilos/$styleSlug': {
      id: '/estilos/$styleSlug'
      path: '/estilos/$styleSlug'
      fullPath: '/estilos/$styleSlug'
      preLoaderRoute: typeof EstilosStyleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambientes/$roomSlug': {
      id: '/ambientes/$roomSlug'
      path: '/ambientes/$roomSlug'
      fullPath: '/ambientes/$roomSlug'
      preLoaderRoute: typeof AmbientesRoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receita': {
      id: '/admin/receita'
      path: '/receita'
      fullPath: '/admin/receita'
      preLoaderRoute: typeof AdminReceitaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projetos': {
      id: '/admin/projetos'
      path: '/projetos'
      fullPath: '/admin/projetos'
      preLoaderRoute: typeof AdminProjetosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creditos': {
      id: '/admin/creditos'
      path: '/creditos'
      fullPath: '/admin/creditos'
      preLoaderRoute: typeof AdminCreditosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/afiliados': {
      id: '/admin/afiliados'
      path: '/afiliados'
      fullPath: '/admin/afiliados'
      preLoaderRoute: typeof AdminAfiliadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/estilos/$styleSlug/$roomSlug': {
      id: '/estilos/$styleSlug/$roomSlug'
      path: '/$roomSlug'
      fullPath: '/estilos/$styleSlug/$roomSlug'
      preLoaderRoute: typeof EstilosStyleSlugRoomSlugRouteImport
      parentRoute: typeof EstilosStyleSlugRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminAfiliadosRoute: typeof AdminAfiliadosRoute
  AdminCreditosRoute: typeof AdminCreditosRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminProjetosRoute: typeof AdminProjetosRoute
  AdminReceitaRoute: typeof AdminReceitaRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAfiliadosRoute: AdminAfiliadosRoute,
  AdminCreditosRoute: AdminCreditosRoute,
  AdminInsightsRoute: AdminInsightsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminProjetosRoute: AdminProjetosRoute,
  AdminReceitaRoute: AdminReceitaRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EstilosStyleSlugRouteChildren {
  EstilosStyleSlugRoomSlugRoute: typeof EstilosStyleSlugRoomSlugRoute
}

const EstilosStyleSlugRouteChildren: EstilosStyleSlugRouteChildren = {
  EstilosStyleSlugRoomSlugRoute: EstilosStyleSlugRoomSlugRoute,
}

const EstilosStyleSlugRouteWithChildren =
  EstilosStyleSlugRoute._addFileChildren(EstilosStyleSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  OrcamentoDesignInterioresRoute: OrcamentoDesignInterioresRoute,
  ParaArquitetosRoute: ParaArquitetosRoute,
  ParaDesignersRoute: ParaDesignersRoute,
  ParaImobiliariasRoute: ParaImobiliariasRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AmbientesRoomSlugRoute: AmbientesRoomSlugRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  EstilosStyleSlugRoute: EstilosStyleSlugRouteWithChildren,
  PProjectIdRoute: PProjectIdRoute,
  VsPlanner5dRoute: VsPlanner5dRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
